- name: Deploy project
  hosts: all

  become: yes
  tasks:
  - name: Remove old build
    ansible.builtin.file:
      path: /var/lib/tomcat10/webapps/ROOT
      state: absent

  - name: Deploy new build
    ansible.builtin.unarchive:
      src: ROOT.tar.gz
      dest: /var/lib/tomcat10/webapps/
      owner: tomcat
      group: tomcat
      mode: u=rwx,g=rwx,o=rx
      
