# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn package

    - name: Configure SSH
      uses: ./.github/actions/configure-ssh
      with:
        SSH_KEY:  ${{ secrets.SSH_KEY }}
        SSH_USER:  ${{ secrets.SSH_USER }}
        SSH_HOST:  ${{ secrets.SSH_HOST }}
        
    - name: Move build folder
      run: "sudo ./scripts/move-file target/ ROOT"

    - name: Deploy project
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        directory: ./scripts/
        key: ${{secrets.SSH_KEY}}
        inventory: |
          [all]
          prod
        options: |
          --inventory .hosts
